/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
  interface UkAccordion {}
  interface UkCountdown {}
  interface UkDrop {}
  interface UkDropbar {}
  interface UkDropnav {}
  interface UkLeader {}
  interface UkModal {}
  interface UkNotification {}
  interface UkOffcanvas {}
  interface UkSlider {}
  interface UkSlideshow {}
  interface UkSortable {}
  interface UkSticky {}
  interface UkSwitcher {
    active: number;
    connect: string;
  }
  interface UkSwitcherItem {
    active: boolean;
    disabled: boolean;
  }
  interface UkTab {
    active: number;
    name: string;
    variant: "top" | "bottom" | "left" | "right";
  }
  interface UkTabItem {
    active: boolean;
    disabled: boolean;
  }
  interface UkTooltip {}
}
declare global {
  interface HTMLUkAccordionElement
    extends Components.UkAccordion,
      HTMLStencilElement {}
  var HTMLUkAccordionElement: {
    prototype: HTMLUkAccordionElement;
    new (): HTMLUkAccordionElement;
  };
  interface HTMLUkCountdownElement
    extends Components.UkCountdown,
      HTMLStencilElement {}
  var HTMLUkCountdownElement: {
    prototype: HTMLUkCountdownElement;
    new (): HTMLUkCountdownElement;
  };
  interface HTMLUkDropElement extends Components.UkDrop, HTMLStencilElement {}
  var HTMLUkDropElement: {
    prototype: HTMLUkDropElement;
    new (): HTMLUkDropElement;
  };
  interface HTMLUkDropbarElement
    extends Components.UkDropbar,
      HTMLStencilElement {}
  var HTMLUkDropbarElement: {
    prototype: HTMLUkDropbarElement;
    new (): HTMLUkDropbarElement;
  };
  interface HTMLUkDropnavElement
    extends Components.UkDropnav,
      HTMLStencilElement {}
  var HTMLUkDropnavElement: {
    prototype: HTMLUkDropnavElement;
    new (): HTMLUkDropnavElement;
  };
  interface HTMLUkLeaderElement
    extends Components.UkLeader,
      HTMLStencilElement {}
  var HTMLUkLeaderElement: {
    prototype: HTMLUkLeaderElement;
    new (): HTMLUkLeaderElement;
  };
  interface HTMLUkModalElement extends Components.UkModal, HTMLStencilElement {}
  var HTMLUkModalElement: {
    prototype: HTMLUkModalElement;
    new (): HTMLUkModalElement;
  };
  interface HTMLUkNotificationElement
    extends Components.UkNotification,
      HTMLStencilElement {}
  var HTMLUkNotificationElement: {
    prototype: HTMLUkNotificationElement;
    new (): HTMLUkNotificationElement;
  };
  interface HTMLUkOffcanvasElement
    extends Components.UkOffcanvas,
      HTMLStencilElement {}
  var HTMLUkOffcanvasElement: {
    prototype: HTMLUkOffcanvasElement;
    new (): HTMLUkOffcanvasElement;
  };
  interface HTMLUkSliderElement
    extends Components.UkSlider,
      HTMLStencilElement {}
  var HTMLUkSliderElement: {
    prototype: HTMLUkSliderElement;
    new (): HTMLUkSliderElement;
  };
  interface HTMLUkSlideshowElement
    extends Components.UkSlideshow,
      HTMLStencilElement {}
  var HTMLUkSlideshowElement: {
    prototype: HTMLUkSlideshowElement;
    new (): HTMLUkSlideshowElement;
  };
  interface HTMLUkSortableElement
    extends Components.UkSortable,
      HTMLStencilElement {}
  var HTMLUkSortableElement: {
    prototype: HTMLUkSortableElement;
    new (): HTMLUkSortableElement;
  };
  interface HTMLUkStickyElement
    extends Components.UkSticky,
      HTMLStencilElement {}
  var HTMLUkStickyElement: {
    prototype: HTMLUkStickyElement;
    new (): HTMLUkStickyElement;
  };
  interface HTMLUkSwitcherElement
    extends Components.UkSwitcher,
      HTMLStencilElement {}
  var HTMLUkSwitcherElement: {
    prototype: HTMLUkSwitcherElement;
    new (): HTMLUkSwitcherElement;
  };
  interface HTMLUkSwitcherItemElement
    extends Components.UkSwitcherItem,
      HTMLStencilElement {}
  var HTMLUkSwitcherItemElement: {
    prototype: HTMLUkSwitcherItemElement;
    new (): HTMLUkSwitcherItemElement;
  };
  interface HTMLUkTabElement extends Components.UkTab, HTMLStencilElement {}
  var HTMLUkTabElement: {
    prototype: HTMLUkTabElement;
    new (): HTMLUkTabElement;
  };
  interface HTMLUkTabItemElement
    extends Components.UkTabItem,
      HTMLStencilElement {}
  var HTMLUkTabItemElement: {
    prototype: HTMLUkTabItemElement;
    new (): HTMLUkTabItemElement;
  };
  interface HTMLUkTooltipElement
    extends Components.UkTooltip,
      HTMLStencilElement {}
  var HTMLUkTooltipElement: {
    prototype: HTMLUkTooltipElement;
    new (): HTMLUkTooltipElement;
  };
  interface HTMLElementTagNameMap {
    "uk-accordion": HTMLUkAccordionElement;
    "uk-countdown": HTMLUkCountdownElement;
    "uk-drop": HTMLUkDropElement;
    "uk-dropbar": HTMLUkDropbarElement;
    "uk-dropnav": HTMLUkDropnavElement;
    "uk-leader": HTMLUkLeaderElement;
    "uk-modal": HTMLUkModalElement;
    "uk-notification": HTMLUkNotificationElement;
    "uk-offcanvas": HTMLUkOffcanvasElement;
    "uk-slider": HTMLUkSliderElement;
    "uk-slideshow": HTMLUkSlideshowElement;
    "uk-sortable": HTMLUkSortableElement;
    "uk-sticky": HTMLUkStickyElement;
    "uk-switcher": HTMLUkSwitcherElement;
    "uk-switcher-item": HTMLUkSwitcherItemElement;
    "uk-tab": HTMLUkTabElement;
    "uk-tab-item": HTMLUkTabItemElement;
    "uk-tooltip": HTMLUkTooltipElement;
  }
}
declare namespace LocalJSX {
  interface UkAccordion {}
  interface UkCountdown {}
  interface UkDrop {}
  interface UkDropbar {}
  interface UkDropnav {}
  interface UkLeader {}
  interface UkModal {}
  interface UkNotification {}
  interface UkOffcanvas {}
  interface UkSlider {}
  interface UkSlideshow {}
  interface UkSortable {}
  interface UkSticky {}
  interface UkSwitcher {
    active?: number;
    connect?: string;
  }
  interface UkSwitcherItem {
    active?: boolean;
    disabled?: boolean;
  }
  interface UkTab {
    active?: number;
    name?: string;
    variant?: "top" | "bottom" | "left" | "right";
  }
  interface UkTabItem {
    active?: boolean;
    disabled?: boolean;
  }
  interface UkTooltip {}
  interface IntrinsicElements {
    "uk-accordion": UkAccordion;
    "uk-countdown": UkCountdown;
    "uk-drop": UkDrop;
    "uk-dropbar": UkDropbar;
    "uk-dropnav": UkDropnav;
    "uk-leader": UkLeader;
    "uk-modal": UkModal;
    "uk-notification": UkNotification;
    "uk-offcanvas": UkOffcanvas;
    "uk-slider": UkSlider;
    "uk-slideshow": UkSlideshow;
    "uk-sortable": UkSortable;
    "uk-sticky": UkSticky;
    "uk-switcher": UkSwitcher;
    "uk-switcher-item": UkSwitcherItem;
    "uk-tab": UkTab;
    "uk-tab-item": UkTabItem;
    "uk-tooltip": UkTooltip;
  }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      "uk-accordion": LocalJSX.UkAccordion &
        JSXBase.HTMLAttributes<HTMLUkAccordionElement>;
      "uk-countdown": LocalJSX.UkCountdown &
        JSXBase.HTMLAttributes<HTMLUkCountdownElement>;
      "uk-drop": LocalJSX.UkDrop & JSXBase.HTMLAttributes<HTMLUkDropElement>;
      "uk-dropbar": LocalJSX.UkDropbar &
        JSXBase.HTMLAttributes<HTMLUkDropbarElement>;
      "uk-dropnav": LocalJSX.UkDropnav &
        JSXBase.HTMLAttributes<HTMLUkDropnavElement>;
      "uk-leader": LocalJSX.UkLeader &
        JSXBase.HTMLAttributes<HTMLUkLeaderElement>;
      "uk-modal": LocalJSX.UkModal & JSXBase.HTMLAttributes<HTMLUkModalElement>;
      "uk-notification": LocalJSX.UkNotification &
        JSXBase.HTMLAttributes<HTMLUkNotificationElement>;
      "uk-offcanvas": LocalJSX.UkOffcanvas &
        JSXBase.HTMLAttributes<HTMLUkOffcanvasElement>;
      "uk-slider": LocalJSX.UkSlider &
        JSXBase.HTMLAttributes<HTMLUkSliderElement>;
      "uk-slideshow": LocalJSX.UkSlideshow &
        JSXBase.HTMLAttributes<HTMLUkSlideshowElement>;
      "uk-sortable": LocalJSX.UkSortable &
        JSXBase.HTMLAttributes<HTMLUkSortableElement>;
      "uk-sticky": LocalJSX.UkSticky &
        JSXBase.HTMLAttributes<HTMLUkStickyElement>;
      "uk-switcher": LocalJSX.UkSwitcher &
        JSXBase.HTMLAttributes<HTMLUkSwitcherElement>;
      "uk-switcher-item": LocalJSX.UkSwitcherItem &
        JSXBase.HTMLAttributes<HTMLUkSwitcherItemElement>;
      "uk-tab": LocalJSX.UkTab & JSXBase.HTMLAttributes<HTMLUkTabElement>;
      "uk-tab-item": LocalJSX.UkTabItem &
        JSXBase.HTMLAttributes<HTMLUkTabItemElement>;
      "uk-tooltip": LocalJSX.UkTooltip &
        JSXBase.HTMLAttributes<HTMLUkTooltipElement>;
    }
  }
}
