/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {}
declare global {
  type HTMLElementTagNameMap = {};
}
declare namespace LocalJSX {
  type IntrinsicElements = {};
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
  export namespace JSX {
    type IntrinsicElements = {};
  }
}
